### ISSUE TITLE
TODO (from initial implementation)

### ISSUE THREAD

**Issue by junderw** [junderw/tiny-secp256k1-wasm#9]
Upstream waits:

1. Wait on https://github.com/rust-bitcoin/rust-secp256k1/pull/219 and use it to get around `Message` restrictions. (Requires some messing around on our end) (I made a workaround on my fork of rust-secp256k1)
2. Wait on https://github.com/rust-bitcoin/rust-secp256k1/pull/220 (already merged on my fork)

TODO:

- [ ] Fix isPoint with uncompressed pubkey performance
- [x] Fix isPrivate performance
- [x] Add more arg variants to benches to make sure changing the inputs doesn't make us slower (like isPoint... we are faster with compressed pubkey for some reason)
- [ ] Figure out how to package this / what build scripts to use... (perhaps docker would be better, to prevent environment discrepancies during build process...?)

**Comment by junderw** [comment]
The two upstream waits are now merged.

Once I get some time, I want to switch from my fork back to the main upstream.
